config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
	enum status: { draft: 0, inprogress: 1, completed: 2 }
	
	validates :title, presence: true

	default_scope { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
    @draft_todos = @todos.draft
    @inprogress_todos = @todos.inprogress
    @completed_todos = @todos.completed
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream{
          render turbo_stream: [
            turbo_stream.prepend("draft-todos", @todo),
            turbo_stream.update("todos-counter", html: Todo.count)
          ]
        }
        
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.turbo_stream{
        render turbo_stream: [
          turbo_stream.remove(@todo),
          turbo_stream.update("todos-counter", html: Todo.count)
        ]
      }
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :string, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoWithTurbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= turbo_frame_tag "todo-form#{todo.id}" do %>
  <%= form_with(model: todo) do |form| %>
    <div class="form">
      <%= form.text_field :title, class: 'input', placeholder: 'Add a task' %>
      <% unless todo.new_record? %>
        <%= form.select :status, options_for_select(Todo.statuses.keys, todo.status), {}, {class: 'input'} %>
      <%end%>
      <%= form.submit "#{ todo.new_record? ? 'Add' : 'Update'}", class: 'add' %>
      <%= link_to 'Cancel', todo_path(todo), class: 'cancel' unless todo.new_record?%>
    </div>
  <% end %>
<%end%>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag "todo-form#{todo.id}" do %>
  <div id="<%= dom_id todo %>" class="task">
    <div><%= todo.title %> 
      <!-- <span class="status <%=todo.status%>"><%=todo.status%></span> -->
    </div>
    
    <ul style="display: flex;" class="action-links">
      <li><%= link_to "edit", edit_todo_path(todo) %></li>
      <li><%= button_to "Delete", todo, { method: :delete, class: 'del', form: { data: { turbo_confirm: 'Are you sure?'}}} %></li>
    </ul>
  </div>
<%end%>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<div id="form-section">
  <%= render 'form', todo: (@todo || Todo.new) %>
</div>

<div class="flex space-around">
  <div id="draft-todos" class="tasks">
    <h2>Todo (<span id='todos-counter-draft'><%=@draft_todos.count%></span>)</h2>
    <%= render partial: 'todo', collection: @draft_todos %>
  </div>

  <div id="inprogress-todos" class="tasks">
    <h2>In Progress (<span id='todos-counter-inprogress'><%=@inprogress_todos.count%></span>)</h2>
    <%= render partial: 'todo', collection: @inprogress_todos %>
  </div>

  <div id="completed-todos" class="tasks">
    <h2>Completed (<span id='todos-counter-completed'><%=@completed_todos.count%></span>)</h2>
    <%= render partial: 'todo', collection: @completed_todos %>
  </div>
</div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.append "#{@todo.status}-todos" do %>
    <%= render "todos/todo", todo: @todo %>
<% end %>

<%= turbo_stream.remove "todo-form#{@todo.id}" %>